# Generated by Django 3.0.6 on 2021-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descripton',
            field=models.TextField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/'),
        ),
    ]
